HRMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from account.views import *

urlpatterns = [
    path("",UserLogin.as_view(),name="login"),
    path("log-out/",UserLogOut.as_view(),name="logout"),
    # path("location/", UserLocation.as_view(), name="location"),
    path("admin/", admin.site.urls),
    path("accounts/",include('account.urls')),
    path("payroll/",include('payroll.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404= 'account.views.error_404'

payroll/urls.py
from django.urls import path
from payroll.views import *



urlpatterns = [
    # leaves
    path("leave-applications/",LeaveApplications.as_view(),name="leave_applications"),
    path("leave-applications/<int:pk>",ApproveLeaves.as_view(),name="approve_leaves"),
    path("employee-leave-history/", EmployeeLeavesHistory.as_view(), name="employee_leave_history"),
    
    # attendance
    path("missing-attendance-applications/", MissingAttendanceApplications.as_view(), name = "missing_attendance_applications"),
    path("missing-attendance-history/", MissingAttendanceApplicationsHistory.as_view(), name = "missing_attendance_application_history"),
    path("attendance-applications/",ApproveAttendance.as_view(),name="attendance_applications"),
    path("attendance-list/", AttendanceList.as_view(), name="attendance_list"),
    path("emp-attendance-history/<str:pk>/", AttendanceHistoryEmp.as_view(), name="emp_attendance_history"),
    path("today-attendance-list/", TodayAttendanceList.as_view(), name="today_attendance_list"),
    
    # employees
    path("all-users/", EmployeeList.as_view(), name = 'all_users'),
    path("update-employee/<int:pk>",UpdateEmployee.as_view(), name="update_employee" ),
    path("verify-details/",VerifyDetails.as_view(),name="verify_details"),
    
    # payroll
    path("payroll/", PayrollData.as_view(), name = "payroll"),
    path('day-based-salary/', DayBasedSalary.as_view(), name = "day_based_salary"),
    path('department-based-salary/', DepartmentBasedSalary.as_view(), name = "department_based_salary"),
    path('time-based-salary/', TimeBasedSalary.as_view(), name="time_based_salary"),
    path('total-paid-salary/', SalariesPaidTillDate.as_view(), name="total_paid_salary"),
    
    # other
    path("department/", DepartmentDetails.as_view(),name="department"),
    path("designation/", DesignationDetails.as_view(),name="designation"),
    path("shift/", Shift.as_view(), name="shift"),
    
    # teams
    path("teams/", Team.as_view(),name="teams"),
    path('add-team/', AddTeam.as_view(), name = "add_team"),
    path("update-team/<int:id>/", UpdateTeam.as_view(), name="update_team"),
    path("team-members/", TeamMembers.as_view(),name="team_members"),
    
    # policy
    path("policy/", Policy.as_view(), name="policy"),
    
    # dashboards
    path("team-leader-dashboard/", TeamLeaderDashboard.as_view(), name = "team_leader_dashboard"),
    path("ems-dashboard/", HREMSDashboard.as_view(), name = "ems_dashboard"),
    path("leaves-dashboard/", HRLeavesDashboard.as_view(), name='leaves_dashboard'),
    path("attendance-dashboard/", HRAttendanceDashboard.as_view(), name='attendance_dashboard'),
    path("payroll-dashboard/", HRPayrollDashboard.as_view(), name='payroll_dashboard'),
    path("create-employee-dashboard/", HRCreateEmployeeDashboard.as_view(), name='create_employee_dashboard'),
    path("hr-analytics/", HrAnalytics.as_view(), name='hr_analytics'),
    path("hr-info/", data, name='hr_info'),
    
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime
from payroll.models import DailyAttendance

class Designation(models.Model):
    designation_name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.designation_name
    
class Department(models.Model):
    department_name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.department_name
    
class UserShiftDetails(models.Model):
    shift_name = models.CharField(max_length=100, unique=True)
    in_time = models.TimeField()
    out_time = models.TimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.shift_name

class UserBasicDetails(models.Model):
    emp_user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_basics')
    designation = models.ForeignKey(Designation, on_delete=models.CASCADE, to_field='designation_name',related_name='user_designation_details', null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, to_field='department_name',related_name='user_department_details', null=True)
    shift_details = models.ForeignKey(UserShiftDetails, on_delete=models.CASCADE, to_field='shift_name',related_name='user_shift_details', null=True)
    date_of_joining = models.DateField(auto_now=True, null=True)
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    uan_number = models.BigIntegerField(null=True)
    pf_number = models.CharField(max_length=10, null=True)
    experience_status = models.CharField (choices=(("Fresher", "Fresher"), ("Experienced", "Experienced")), max_length=50, null=True)
    is_salaried = models.BooleanField(default=True)   #if salaried is True deduction part for employee will be calculated eg. PF.
    is_active = models.BooleanField(default=True)
    is_approved = models.BooleanField(default=False)
    is_verify = models.BooleanField(default=False)
    is_requested = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='employee_created_by', null=True)
    approved_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='employee_approved_by', null=True)
    is_completed_basic_details = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.emp_user.username
    
class PreviousOrganisationDetail(models.Model):
    emp_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_previous_details')
    experience_in_years = models.IntegerField(null=True)
    previous_organisation = models.CharField(max_length=255, null=True)
    previous_organisation_designation = models.CharField(max_length=100, null=True)
    is_completed_previous_organisation_details = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.emp_user.username
    
class UserAdditionalDetail(models.Model):
    emp_user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_additional_details')
    gender = models.CharField(choices=(('Male' , 'Male'), ('Female', 'Female')), max_length=55, null=True)
    mobile_no = models.BigIntegerField(null=True)
    date_of_birth = models.DateField(null=True)
    pan_number = models.CharField(max_length=10, null=True)
    aadhaar_number = models.BigIntegerField(null=True)
    permanent_address = models.TextField(null=True)
    current_address = models.TextField(null=True)
    marital_status = models.CharField(choices=(('Single', 'Single'), ('Married', 'Married')), max_length=55, null=True)
    passport_no = models.CharField(max_length=9, null=True)
    father_name = models.CharField(max_length=255, null=True)
    mother_name = models.CharField(max_length=255, null=True)
    nationality = models.CharField(max_length=50, null=True)
    emergency_contact_no = models.BigIntegerField(null=True)
    blood_group = models.CharField(max_length=3, null=True)
    profile_photo = models.ImageField(upload_to='userprofile', null=True, default='default_profile_pic.png')
    is_requested = models.BooleanField(default=False) 
    is_completed_additional_details = models.BooleanField(default=False)  # this will become True if mandatory fields are filled by employee after verification by HR
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.emp_user.username
    
class UserBankDetail(models.Model):
    emp_user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_bank_details')
    bank_name = models.CharField(max_length=255, null=True)
    branch_name = models.CharField(max_length=100, null=True)
    account_type = models.CharField(choices=(('Current', 'Current'), ('Saving', 'Saving')), max_length=25, null=True)
    ifsc_code = models.CharField(max_length=11, null=True)
    account_number = models.BigIntegerField(null=True)
    is_completed_bank_details = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.emp_user.username
    
class UserDocument(models.Model):
    emp_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_docs")
    doc_name = models.CharField(max_length=200, default='document')
    doc_file = models.FileField(upload_to='userdocs')
    is_completed_docs = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.emp_user.username + ' ' + self.doc_name
    
class DocumentRemark(models.Model):
    emp_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users_docs_remark')
    remark = models.TextField()
    is_full_filled = models.BooleanField(default=False) # if there is any issue in uploaded docs by user HR will add remark to replace those docs & this field will True docs are ok 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.emp_user.username+ ' ' + self.remark
    
class UserEducationDetails(models.Model):
    emp_user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_academics')
    ssc_board_name = models.CharField(max_length=255, null=True)
    ssc_school_name = models.CharField(max_length=255, null=True)
    ssc_percentage = models.IntegerField(default=0, null=True)
    ssc_passing_yr = models.IntegerField(default=0,null=True)
    hsc_board_name = models.CharField(max_length=255, null=True)
    hsc_school_name = models.CharField(max_length=255, null=True)
    hsc_percentage = models.IntegerField(default=0,null=True)
    hsc_passing_yr = models.IntegerField(default=0,null=True)
    hsc_stream = models.CharField(choices=(('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce')), max_length=55, null=True)
    diploma_university = models.CharField(max_length=255, null=True)
    diploma_college = models.CharField(max_length=255, null=True)
    diploma_branch = models.CharField(max_length=100, null=True)
    diploma_admission_yr = models.IntegerField(default=0,null=True)
    diploma_passout_yr = models.IntegerField(default=0,null=True)
    diploma_percentage = models.IntegerField(default=0,null=True)
    graduation_university = models.CharField(max_length=255, null=True)
    graduation_college = models.CharField(max_length=255, null=True)
    graduation_branch = models.CharField(max_length=100, null=True)
    graduation_admission_yr = models.IntegerField(default=0,null=True)
    graduation_passout_yr = models.IntegerField(default=0,null=True)
    graduation_percentage = models.IntegerField(default=0,null=True)
    pg_university = models.CharField(max_length=255, null=True)
    pg_college = models.CharField(max_length=255, null=True)
    pg_branch = models.CharField(max_length=100,null=True)
    pg_admission_yr = models.IntegerField(default=0,null=True)
    pg_passout_yr = models.IntegerField(default=0,null=True)
    pg_percentage = models.IntegerField(default=0,null=True)
    is_completed_academics = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.emp_user.first_name+ ' ' + self.emp_user.last_name +' '+ self.emp_user.username

class Teams(models.Model):
    team_name = models.CharField(max_length= 100)
    employees = models.ManyToManyField(User)
    leader_name = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_leader_name')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.team_name
    
class EmployeePermissions(models.Model):
    emp_user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='employee_permissions_user')
    can_approve_attendance = models.BooleanField(default=False)
    can_approve_leaves = models.BooleanField(default=False)
    can_manage_employee = models.BooleanField(default=False)

payroll/forms.py
from django import forms
from account.models import Teams

class TeamsForm(forms.ModelForm):
    class Meta:
        model = Teams
        fields = ["team_name", "leader_name", "employees","is_active"]
        

payroll/views.py
from payroll.payroll_views.emp_management.manage_leaves import *
from payroll.payroll_views.emp_management.approve_attendance import *
from payroll.payroll_views.emp_management.department import *
from payroll.payroll_views.emp_management.designation import *
from payroll.payroll_views.emp_management.payroll import *
from payroll.payroll_views.hr_analytics.hr_analytics import *
from payroll.payroll_views.emp_management.missing_attendance import *
from payroll.payroll_views.emp_management.teams import *
from payroll.payroll_views.emp_management.team_members import *
from payroll.payroll_views.emp_management.employee_list import *
from payroll.payroll_views.emp_management.shift import *
from payroll.payroll_views.emp_management.update_employee import *
from payroll.payroll_views.emp_management.verify_details import *
from payroll.payroll_views.emp_management.employees_leave_history import *


from payroll.payroll_views.admin_dashboards.admin_dashboard import *

templates/payroll/emp_management/department.html
{% extends 'hr_profile_basic.html' %}
{% load static %}

{% block tag %}
<link href="{%static 'css/self-details.css'%}" rel="stylesheet">
<link href="{%static 'css/forms.css'%}" rel="stylesheet">
{% endblock %}

<title>{% block title %} HRMS : Departments {% endblock %}</title>

{% block style %}

<style>
    .user-info {
        padding: 2rem;
        overflow: auto;
    }

    .user_info {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-between;
        padding: 0 1rem;
    }

    .basic_info {
        width: 100%;
    }

    .main-heading {
        margin: 0;
    }

    .user_info .info {
        max-width: 40%;
        display: flex;
        justify-content: space-between;
        padding: 0;
        padding-bottom: 0.5em;
        border-bottom: 1px solid #ddd;
    }

    .user_info .info .info-description {
        margin-right: 1rem;

    }

    .user_info .info p {
        margin: 0;
    }

    .info-full {
        max-width: 100%;
        padding: 0 1rem;

    }

    .card {
        border: 1px solid #387EF9;
        border-radius: 0px;
        padding: 1rem;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
    }

    .card p {
        margin: 0;
        color: #444;
        font-weight: 500;
        margin-left: 1rem;
    }



    .table .next-btn2 {
        margin: 0;
        padding: 0.2em 1em;
        font-size: 1em;
        font-weight: 500;
        border: 2px solid #387EF9;
        transition: 0.2s linear;
    }

    .table .next-btn2:hover {
        background: #fff;
        color: #387EF9;
        border: 2px solid #387EF9;
        transition: 0.2s linear;
    }

    tbody .input_value {
        border: none;
        outline: none;
        border: 1px solid #ddd;
        padding: 0.3em 0.8em;
        color: #444;

    }
    .table thead th {
        text-align: left;
    }

    .table tbody td {
        padding: 0.5em 25px;
        vertical-align: middle; 
        border: none;
        text-align: left;
    }

    .table tr{
        border-bottom: 1px solid #ddd;
    }



    .input_item {
        border: none;
        background: #fff;
    }

    .table tbody .display_hidden {
        display: none;
    }

    .form_action_btns {
        display: flex;
        align-items: center;
        justify-content: space-evenly;
    }

    .form_action_btns .icon_button {
        outline: none;
        border: none;
        border: 1px solid #ddd;
        background:#ddd;
        color: #444;
        border-radius: 50%;
    }

    .table .material-symbols-outlined {
        padding: 0.3em;
        color: #444;
        cursor: pointer;
    }


</style>



{% endblock %}

{% block profile %}


<section class="user-info">
    <div class="basic_info">

        <div class="head-card">
            <h4>Department Details</h4>
            <a href="{% url 'ems_dashboard' %}">
                Back
                <span class="material-symbols-outlined mx-2">
                    undo
                </span>
            </a>
        </div>

        <form class="user_input_form my-lg-5" action="{% url 'department' %}" method="post">{% csrf_token %}


            <div class="input_box ">
                <p class="input_title">Department Name</p>
                <input type="hidden" name="dept_id">
                <input type="text" class="input_value" id="reason" name="dept_name" placeholder="Enter a department"
                    required>
            </div>

            <button type="submit" name="type" value="create" class="next_btn2">Submit</button>

        </form>


    </div>


    {% if departments %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Sr. No.</th>
                <th scope="col">Department Name</th>
                <th scope="col" style="text-align: center;">Actions</th>
            </tr>
        </thead>


        <tbody>
            {% for dept in departments %}
            <tr>
                <form action="{% url 'department' %}" method="post">{% csrf_token %}

                    <td>{{forloop.counter}}</td>

                    <td id="dept_inputs{{dept.id}}">

                        <input type="hidden" name="dept_id" value="{{dept.id}}" disabled>
                        <input type="text" class="input_item" name="dept_name" value="{{dept.department_name}}" required
                            disabled>

                    </td>

                    <td class="form_action_btns">

                        <div class="buttons_div display_hidden" id="dept_update_buttons{{dept.id}}">
                            <button type="submit" class="icon_button" name="type" value="update"><span
                                    class="material-symbols-outlined" style="color:#387EF9">upgrade</span></button>
                            <button type="submit" class="icon_button" name="type" value="delete"><span
                                    class="material-symbols-outlined" style="color:red">delete</span></button>
                        </div>


                        <span class="material-symbols-outlined cancel_button display_hidden icon_button"
                            id="cancel_button{{dept.id}}" onclick="editDept('{{dept.id}}','cancel')">
                            close
                        </span>

                        <span class="material-symbols-outlined edit_button icon_button" id="edit_button{{dept.id}}"
                            onclick="editDept('{{dept.id}}','update')">

                            drive_file_rename_outline

                        </span>
                    </td>

                </form>

            </tr>
            {% endfor %}

        </tbody>
    </table>

    {% endif %}

</section>


{% endblock %}


{% block js %}
<script>

    document.getElementById('dashboard').classList.add('link1');

    function editDept(id, action) {
        var edit_button = document.getElementById('edit_button' + id);
        var cancel_button = document.getElementById('cancel_button' + id);
        var dept_update_buttons = document.getElementById('dept_update_buttons' + id);
        var inputs = document.querySelector('#dept_inputs' + id).querySelectorAll('input')


        console.log(id)

        if (action == 'update') {


            edit_button.classList.add("display_hidden")
            cancel_button.classList.remove("display_hidden")
            dept_update_buttons.classList.remove("display_hidden")

            for (var i = 0; i < inputs.length; i++) {
                inputs[i].disabled = false;
                inputs[i].classList.add("input_value")
                inputs[i].classList.remove("input_item")
            }

        } else {

            edit_button.classList.remove("display_hidden")
            cancel_button.classList.add("display_hidden")
            dept_update_buttons.classList.add("display_hidden")

            for (var i = 0; i < inputs.length; i++) {
                inputs[i].disabled = true;
                inputs[i].classList.add("input_item")
                inputs[i].classList.remove("input_value")
            }
        }


    }
</script>
{% endblock %}

templates/payroll/emp_management/department_based_salary.html
{% extends 'profile_basic.html' %}
{% load static %}

{% block tag %}
<link href="{%static 'css/self-details.css'%}" rel="stylesheet">
{% endblock %}

<title>{% block title %} HRMS : Department Based Salary {% endblock %}</title>

{% block style %}

<style>
     .team-members {
          width: 100%;
          min-height: 100vh;
          height: 100%;
          overflow: auto;
          padding: 2em;
     }

     :root {
        --red: hsl(0, 78%, 62%);
        --cyan: hsl(180, 62%, 55%);
        --orange: hsl(34, 97%, 64%);
        --blue: hsl(212, 86%, 64%);
        --varyDarkBlue: hsl(234, 12%, 34%);
        --grayishBlue: hsl(229, 6%, 66%);
        --veryLightGray: hsl(0, 0%, 98%);
        --weight1: 200;
        --weight2: 400;
        --weight3: 600;
    }

     .members {
          display: flex;
          align-items: center;
          justify-content: center;
          flex-wrap: wrap;
          gap: 2rem;
          width: 100%;
          height: 100%;
     }



     .profile-card {
          flex: 1 1 30%;
          min-width: 24rem;
          max-width: 30rem;
          background: #fff;
          padding: 15px 25px;
          display: flex;
          flex-direction: row;
          align-items: center;
          border-radius: 4px;
          box-shadow: 0 0 2px 0 #ccc;
          transition: .3s;
          margin: 20px 20px;
     }

     .profile-info {
          padding-top: 1rem;
          width: 100%;
     }

     .profile-card:hover {
          transform: scale(1.1);
          box-shadow: 0 0 25px -5px #ccc;
     }

     .profile-icon {
          height: 100px;
          width: 100px;
          object-fit: cover;
          border-radius: 10%;
          margin-right: 2rem;
     }

     .profile-name {
          font-size: 3em;
          font-weight: bold;
     }

     .profile-position {
          font-size: 19px;
          color: #777;
     }

     .button {
          margin: 9px 0 0 0;
          padding: 4px 14px;
          color: #999;
          font-size: 0.7em;
          text-decoration: none;
          border: 1px solid #999;
          border-radius: 4px;
          position: relative;
          top: 8px;
     }

     .cyan {
        border-top: 4px solid var(--cyan);
        border-bottom : 4px solid var(--cyan);
    }

    .red {
        border-top: 4px solid var(--red);
        border-bottom: 4px solid var(--red);
    }

    .blue {
        border-top: 4px solid var(--blue);
        border-bottom: 4px solid var(--blue);
    }

    .orange {
        border-top: 4px solid var(--orange);
        border-bottom: 4px solid var(--orange);
    }


     .button:hover {
          color: #fff;
          background: #748dff;
          border: 1px solid #748dff;
     }

     @media screen and (max-width: 1000px) {
          .profile-name {
               font-size: 18px;
          }
     }

     @media screen and (max-width: 800px) {
          .profile-card {
               padding: 20px 15px;
          }

          .profile-name {
               font-size: 16px;
          }
     }
</style>

{% endblock %}

{% block profile %}


<section class="team-members">
    <div class="head-card">
         <h4>Department Based Salary</h4>
         <a href="{% url 'payroll_dashboard' %}">
              Back
              <span class="material-symbols-outlined mx-2">
                   undo
              </span>
         </a>
    </div>



    <div class="members my-lg-5">

         
        <div class="profile-card blue">
            <img src="{% static 'Logos/backend.jpg' %}" alt="image1" class="profile-icon" />
            <div class="profile-info">
                 <div class="profile-name">₹ {{back_end_development_salary}}</div>
                 <div class="profile-position my-3">Back End Development</div>
            </div>
        </div>

        <div class="profile-card red">
            <img src="{% static 'Logos/soft_test.jpg' %}" alt="image1" class="profile-icon" />
            <div class="profile-info">
                 <div class="profile-name">₹ {{software_testing_salary}}</div>
                 <div class="profile-position my-3">Software Testing</div>
            </div>
        </div>

        <div class="profile-card cyan">
            <img src="{% static 'Logos/sap.png' %}" alt="image1" class="profile-icon" />
            <div class="profile-info">
                 <div class="profile-name">₹ {{sap_salary}}</div>
                 <div class="profile-position my-3">SAP MM</div>
            </div>
        </div>

        <div class="profile-card orange">
            <img src="{% static 'Logos/hr.png' %}" alt="image1" class="profile-icon" />
            <div class="profile-info">
                 <div class="profile-name">₹ {{hr_salary}}</div>
                 <div class="profile-position my-3">Human Resource</div>
            </div>
        </div>

    </div>
</section>

{% endblock %}


{% block js %}
<script>
     document.getElementById('dashboard').classList.add('link1');
</script>
{% endblock %}

templates/payroll/emp_management/update_team.html
{% extends 'hr_profile_basic.html' %}
{% load static %}

{% block tag %}
<link href="{%static 'css/self-details.css'%}" rel="stylesheet">
<link href="{%static 'css/form.css'%}" rel="stylesheet">
{% endblock %}

<title>{% block title %} HRMS : Update Team {% endblock %}</title>

{% block style %}

<style>
    .profile-navigations .profile-navigation-links .link1 {
        color: #fff;
        background-color: #387EF9;
        transition: all 0.5s ease-out;
    }

    .profile-navigations .profile-navigation-links .link1 svg {
        fill: #fff;
        transition: all 0.5s ease-out;
    }

    .details {
        margin-top: 0;
        padding-top: 2rem;
    }

    .details .permissions {
        width: 100%;
        padding: 1.5rem;
    }

    .details .permissions p {
        color: #387EF9;
        font-weight: 500;
        margin-bottom: 1em;
        text-transform: uppercase;
    }

    .details .permissions .check-box-info {
        border-bottom: 1px solid #ddd;
        padding-bottom: 1rem;
    }

    .details .permissions .check-box {
        max-width: 22rem;
        overflow: hidden;
    }

    .check-box-square {
        width: 1.3rem;
        height: 1.3rem;
        transform: translateY(25%);
        margin-right: 1rem;
    }

    .check-box-label:hover {
        cursor: pointer;
    }

    .info-full {
        max-width: 100%;
        padding: 0 1rem;

    }
</style>

{% endblock %}

{% block profile %}




<section class="user-info">
    <form class="details" method="POST" action="{% url 'update_team' team.id %}">{% csrf_token %}

        <div class="heading">
            <h3 class="user-profile-update-title">Update Team</h3>
        </div>

        <div class="info">
            <p class="info-title">Team Name</p>
            <input type="text" name="team_name" value="{{team.team_name}}" maxlength="100" placeholder="Enter team name"
                id="id_team_name" required>
        </div>

        <div class="info">
            <p for="leader_name" class="info-title">Team Leader</p>

            <select class="options" name="leader_name" required id="id_leader_name">
                <option value="" disabled>---------</option>
                {% for leader in employees %}

                {% if leader == team.leader_name %}

                <option value="{{leader.id}}" selected><span style="padding-right:1rem;"> {{leader.get_full_name}}
                    </span> ( {{leader}} )</option>
                {% else %}
                <option value="{{leader.id}}"><span style="padding-right:1rem;"> {{leader.get_full_name}} </span> (
                    {{leader}} )</option>
                {% endif %}

                {% endfor %}
            </select>

        </div>

        <div class="info">
            <p for="is_active" class="info-title">Status</p>

            <select class="options" name="is_active" required id="is_active">
                <option value="" disabled>---------</option>
                
                <option value="Activate" {% if team.is_active %} selected {% endif %}><span style="padding-right:1rem;">Activate</option>
                <option value="Deactivate" {% if not team.is_active %} selected {% endif %}><span style="padding-right:1rem;">Deactivate</option>

            </select>

        </div>




        <div class="permissions">
            <div class="check-box-info">
                <p class="info-title">Select Team Members</p>
                
                {% for employee in employees %}
                <div class="check-box">

                    {% if employee in team.employees.all %}

                    <input type="checkbox" checked class="check-box-square" id="employee{{employee.id}}" name={{employee.username}} value="True">

                    {% else %}

                    <input type="checkbox" class="check-box-square" id="employee{{employee.id}}" name={{employee.username}} value="True">

                    {% endif %}

                    <label class="check-box-label" for="employee{{employee.id}}">{{employee.get_full_name}} ( {{employee.username}} )</label>

                </div>
                {% endfor %}
            </div>
        </div>
        <!-- disabled -->
        <div class="btns">
            <button type="submit" class="next-btn2">Update</button>
        </div>

    </form>
</section>


{% endblock %}

{% block js %}
<script>
    document.getElementById('dashboard').classList.add('link1');
</script>
{% endblock %}